const countryOptions = [
  { key: "in", value: "in", flag: "in", text: "India" },
  { key: "af", value: "af", flag: "af", text: "Afghanistan" },
  { key: "ax", value: "ax", flag: "ax", text: "Aland Islands" },
  { key: "al", value: "al", flag: "al", text: "Albania" },
  { key: "dz", value: "dz", flag: "dz", text: "Algeria" },
  { key: "as", value: "as", flag: "as", text: "American Samoa" },
  { key: "ad", value: "ad", flag: "ad", text: "Andorra" },
  { key: "ao", value: "ao", flag: "ao", text: "Angola" },
  { key: "ai", value: "ai", flag: "ai", text: "Anguilla" },
  { key: "ag", value: "ag", flag: "ag", text: "Antigua" },
  { key: "ar", value: "ar", flag: "ar", text: "Argentina" },
  { key: "am", value: "am", flag: "am", text: "Armenia" },
  { key: "aw", value: "aw", flag: "aw", text: "Aruba" },
  { key: "au", value: "au", flag: "au", text: "Australia" },
  { key: "at", value: "at", flag: "at", text: "Austria" },
  { key: "az", value: "az", flag: "az", text: "Azerbaijan" },
  { key: "bs", value: "bs", flag: "bs", text: "Bahamas" },
  { key: "bh", value: "bh", flag: "bh", text: "Bahrain" },
  { key: "bd", value: "bd", flag: "bd", text: "Bangladesh" },
  { key: "bb", value: "bb", flag: "bb", text: "Barbados" },
  { key: "by", value: "by", flag: "by", text: "Belarus" },
  { key: "be", value: "be", flag: "be", text: "Belgium" },
  { key: "bz", value: "bz", flag: "bz", text: "Belize" },
  { key: "bj", value: "bj", flag: "bj", text: "Benin" },
];

const stateOptions = [
  { key: "Andhra Pradesh", value: "Andhra Pradesh", text: "Andhra Pradesh" },
  {
    value: "Andaman and Nicobar Islands",
    key: "Andaman and Nicobar Islands",
    text: "Andaman and Nicobar Islands",
  },
  {
    value: "Arunachal Pradesh",
    key: "Arunachal Pradesh",
    text: "Arunachal Pradesh",
  },
  { value: "Assam", key: "Assam", text: "Assam" },
  { value: "Bihar", key: "Bihar", text: "Bihar" },
  { value: "Chandigarh", key: "Chandigarh", text: "Chandigarh" },
  { value: "Chhattisgarh", key: "Chhattisgarh", text: "Chhattisgarh" },
  {
    value: "Dadar and Nagar Haveli",
    key: "Dadar and Nagar Haveli",
    text: "Dadar and Nagar Haveli",
  },
  { value: "Daman and Diu", key: "Daman and Diu", text: "Daman and Diu" },
  { value: "Delhi", key: "Delhi", text: "Delhi" },
  { value: "Lakshadweep", key: "Lakshadweep", text: "Lakshadweep" },
  { value: "Puducherry", key: "Puducherry", text: "Puducherry" },
  { value: "Goa", key: "Goa", text: "Goa" },
  { value: "Gujarat", key: "Gujarat", text: "Gujarat" },
  { value: "Haryana", key: "Haryana", text: "Haryana" },
  {
    value: "Himachal Pradesh",
    key: "Himachal Pradesh",
    text: "Himachal Pradesh",
  },
  {
    value: "Jammu and Kashmir",
    key: "Jammu and Kashmir",
    text: "Jammu and Kashmir",
  },
  { value: "Jharkhand", key: "Jharkhand", text: "Jharkhand" },
  { value: "Karnataka", key: "Karnataka", text: "Karnataka" },
  { value: "Kerala", key: "Kerala", text: "Kerala" },
  { value: "Madhya Pradesh", key: "Madhya Pradesh", text: "Madhya Pradesh" },
  { value: "Maharashtra", key: "Maharashtra", text: "Maharashtra" },
  { value: "Manipur", key: "Manipur", text: "Manipur" },
  { value: "Meghalaya", key: "Meghalaya", text: "Meghalaya" },
  { value: "Mizoram", key: "Mizoram", text: "Mizoram" },
  { value: "Nagaland", key: "Nagaland", text: "Nagaland" },
  { value: "Odisha", key: "Odisha", text: "Odisha" },
  { value: "Punjab", key: "Punjab", text: "Punjab" },
  { value: "Rajasthan", key: "Rajasthan", text: "Rajasthan" },
  { value: "Sikkim", key: "Sikkim", text: "Sikkim" },
  { value: "Tamil Nadu", key: "Tamil Nadu", text: "Tamil Nadu" },
  { value: "Telangana", key: "Telangana", text: "Telangana" },
  { value: "Tripura", key: "Tripura", text: "Tripura" },
  { value: "Uttar Pradesh", key: "Uttar Pradesh", text: "Uttar Pradesh" },
  { value: "Uttarakhand", key: "Uttarakhand", text: "Uttarakhand" },
  { value: "West Bengal", key: "West Bengal", text: "West Bengal" },
];

export { countryOptions, stateOptions};
